import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <body className={inter.className}>
        {/* 24.07.19 */}
        <div
          className={
            "bg-indigo-50 desktop:w-screen desktop:h-screen flex justify-center"
          }
        >
          <div className="bg-white desktop:w-screen flex flex-col">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
