import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { AuthProvider } from '../context/AuthContext'; // AuthProvider를 import 합니다.

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-indigo-50 desktop:w-screen desktop:h-screen flex justify-center">
          <div className="bg-white desktop:w-screen flex flex-col">
            <AuthProvider> {/* AuthProvider로 children을 감쌉니다. */}
              {children}
            </AuthProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
